#!/bin/bash

export keymap_patterns="config/*.keymap"         # path to the keymaps to parse
export config_path="keymap_drawer.config.yaml"  # config file, ignored if not exists
export output_folder="images"                      # path to save produced SVGs
export parse_args=""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
export draw_args=""   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"

SRC_PATTERN="config/.*\.(keymap|dtsi|conf)|\.githooks/pre-commit|keymap_drawer\.config\.yaml"

get_args() {
    local keyboard=$2
    eval set -- "$1"
    for arg; do
        local key=${arg%%:*}
        local val=${arg#*:}
        if [ "$key" = "$keyboard" ]; then
            echo "$val"
            break
        fi
    done
}


if git diff --cached --name-only | egrep --quiet "$SRC_PATTERN"
then
    mkdir -p "$output_folder"
    [ -e "$config_path" ] && config_arg=(-c "$config_path") || config_arg=()
    for keymap_file in $keymap_patterns; do
        keyboard=$(basename -s .keymap "$keymap_file")
        echo "INFO: drawing for $keyboard"

        _parse_args=$(get_args "$parse_args" "$keyboard")
        echo "INFO:   got extra parse args: $_parse_args"
        _draw_args=$(get_args "$draw_args" "$keyboard")
        echo "INFO:   got extra draw args: $_draw_args"

        if [ -f "config/${keyboard}.json" ]; then
            echo "INFO:   found config/${keyboard}.json";
            _draw_args+=" -j config/${keyboard}.json"
        fi

        keymap "${config_arg[@]}" parse -z "$keymap_file" $_parse_args >"$output_folder/$keyboard.yaml" \
        && keymap "${config_arg[@]}" draw "$output_folder/$keyboard.yaml" $_draw_args >"$output_folder/$keyboard.svg" \
        && git add "$output_folder/$keyboard.yaml" && git add "$output_folder/$keyboard.svg" \
        || echo "ERROR: parsing or drawing failed for $keyboard!"
    done
fi
