# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#
---
include:
  - board: nice_nano//zmk # comment this if no dongle
    shield: hector36_dongle dongle_display # comment this if no dongle
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano//zmk
    shield: settings_reset
  - board: nice_nano//zmk
    shield: hector36_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n # comment this if no dongle
    # snippet: studio-rpc-usb-uart # uncomment this if no dongle
    # cmake-args: -DCONFIG_ZMK_STUDIO=y # uncomment this if no dongle
  - board: nice_nano//zmk
    shield: hector36_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n