
CONFIG_ZMK_KEYBOARD_NAME="hector36"

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# CONFIG_ZMK_USB=y

# CONFIG_ZMK_BLE=y

CONFIG_ZMK_POINTING=y

# CONFIG_BT_BAS=n # disable battery reporting, mac bug causes this to cause issues with deep sleep

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=n

CONFIG_ZMK_DONGLE_DISPLAY_WPM=y

CONFIG_ZMK_STUDIO=n # If using Feb 2026 firmware with high drain