manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ezxzeng/     # <--- CHANGE REPO
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: pointers_plus_split_battery                # <--- CHANGE REVISION
      import: app/west.yml
  self:
    path: config