manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware/     # <--- CHANGE REPO
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main                # <--- CHANGE REVISION
      import: app/west.yml
  self:
    path: config