manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson/
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: features/pointer-hid-core
      import: app/west.yml
  self:
    path: config